import Link from "next/link";
import { OpenEditorialModeNotice } from "@/components/OpenEditorialModeNotice";
import styles from "@/components/OpenEditorial.module.css";
export default function OpenEditorialPage() {
  return <><header className={styles.hero}><p className="eyebrow">Конституция участия · версия 1.0</p><h1>Открытая редакция<br />будущего</h1><p className={styles.lead}>Эту книгу можно изменить. Заметьте сильную мысль, покажите слабое место, принесите источник или предложите другой ответ. Сейчас можно читать, сохранять мысли для себя и готовить замечания с точной привязкой к тексту.</p><div className={styles.actions}><Link className="button" href="/read/">Читать книгу <span aria-hidden="true">↗</span></Link><Link className="button secondary" href="/open-editorial/manifesto/">Манифест</Link><Link className="text-link" href="/open-editorial/participate/">Подготовить черновик</Link></div></header><OpenEditorialModeNotice />
    <ol className={styles.steps}>{[["01","Вы читаете","Спокойное чтение без регистрации. Участие остаётся вашим выбором."],["02","Замечаете важное","Выделите фрагмент или выберите главу. Точная привязка сохраняет исходную редакцию."],["03","Формулируете мысль","Личная заметка или отдельный черновик вопроса, возражения, исправления."],["04","Сохраняете у себя","Скопируйте замечание или скачайте файл. Текст останется в вашем распоряжении."]].map(([n,title,text]) => <li key={n}><span>{n}</span><h2>{title}</h2><p>{text}</p></li>)}</ol>
    <div className={styles.grid}><section className={styles.panel}><h2>Не обязательно приносить ответ</h2><p>Точное «здесь я перестал понимать» уже задаёт полезный вопрос. Можно оставить запись для себя или подготовить отдельное замечание. Сайт не превращает личную мысль в публичный вклад.</p><div className={styles.actions}><Link className="text-link" href="/open-editorial/me/">Мои заметки в браузере</Link></div></section><section className={styles.panel}><h2>Можно читать со своим ИИ</h2><p>Для вашего агента доступен открытый корпус: фиксированная версия книги, главы и канонические фрагменты. Можно проверить мысль, найти вопрос или подготовить собственный черновик.</p><div className={styles.actions}><Link className="text-link" href="/open-editorial/agents/">Как дать книгу своему ИИ</Link></div></section></div>
    <section className={styles.section}><h2>Манифест описывает следующий шаг</h2><p className={styles.lead}>Открытая редакция предполагает проверку оснований, человеческое решение и видимую судьбу вклада. Публичный приём и этот редакционный процесс ещё не включены.</p><div className={styles.actions}><Link className="text-link" href="/open-editorial/manifesto/">Полный манифест</Link><Link className="text-link" href="/open-editorial/rules/">Что доступно сейчас</Link><Link className="text-link" href="/open-editorial/privacy/">Приватность заметок</Link></div></section>
  </>;
}
