import Link from "next/link";
import { assetPath } from "@/lib/site-config";
import { editorialConnected } from "@/lib/open-editorial-mode";
import { OpenEditorialModeNotice } from "@/components/OpenEditorialModeNotice";
import styles from "@/components/OpenEditorial.module.css";
export const metadata = { title: "Читать со своим ИИ" };
export default async function Page() {
  if (editorialConnected) { const { OpenEditorialAgents } = await import("@/components/OpenEditorialAccount"); return <><header className={styles.hero}><h1>Ваш ИИ — ваш участник</h1><p className={styles.lead}>Открытый текст и явные полномочия владельца.</p></header><section className={styles.section}><OpenEditorialAgents /></section></>; }
  return <><header className={styles.hero}><h1>Читать со своим ИИ</h1><p className={styles.lead}>Дайте своему агенту открытую версию книги. Пусть он поможет понять мысль, проверить основание или подготовить вопрос с точной ссылкой на фрагмент.</p></header><OpenEditorialModeNotice /><div className={styles.grid}><section className={styles.panel}><h2>Книга в машиночитаемом виде</h2><p>Корпус содержит опубликованные главы, канонические блоки, идентификаторы и хеши. Агент может работать с ним без регистрации и ключей доступа.</p><div className={styles.actions}><a className="button secondary" href={assetPath("/editorial/corpus.json")}>Открыть корпус JSON</a><a className="text-link" href={assetPath("/open-editorial/agents/guide.md")}>Руководство для агента</a></div></section><section className={styles.panel}><h2>Подготовленный ответ остаётся у вас</h2><p>Сейчас агент не может отправить вклад на сайт или изменить книгу. Результат своей работы он возвращает вам; черновик можно сохранить самостоятельно. Существенную помощь ИИ стоит обозначить.</p><div className={styles.actions}><Link className="text-link" href="/open-editorial/participate/">Подготовить черновик</Link></div></section></div><div className={styles.actions}><Link className="text-link" href="/open-editorial/agents/guide/">Как устроены версии и привязки</Link><a className="text-link" href={assetPath("/open-editorial/agent-manifest.json")}>Машинное описание возможностей</a></div></>;
}
