"use client";
import { useEffect, useState } from "react";
import { editorialDate, editorialRequest, safeEditorialUrl } from "@/lib/open-editorial";
import { useEditorial } from "./OpenEditorialProvider";
import styles from "./OpenEditorial.module.css";
type PublicItem={id?:string;title?:string;question?:string;change_summary?:string;summary?:string;message?:string;canonical_url?:string;url?:string;published_at?:string;created_at?:string;edition_id?:string;version?:string;display_name?:string};
export function OpenEditorialPublicData({kind}:{kind:"changes"|"tasks"|"participants"|"support"}) {
 const [items,setItems]=useState<PublicItem[]>([]);const [error,setError]=useState("");const [loaded,setLoaded]=useState(false);const {meta}=useEditorial();
 useEffect(()=>{let active=true;const path={changes:"/published-changes",tasks:"/tasks",participants:"/participants",support:"/financial-reports"}[kind];editorialRequest<{items:PublicItem[]}>(path).then(value=>{if(active){setItems(value.items||[]);setLoaded(true);}}).catch(err=>{if(active)setError(err.message);});return()=>{active=false;};},[kind]);
 const empty={changes:["Подтверждённых изменений пока нет","Здесь появятся содержание принятого изменения, ссылка на опубликованную редакцию и признание реального вклада. Статус «принято» сам по себе не создаёт выпуск."],tasks:["Открытые исследования ещё не опубликованы","Исследование появится здесь после согласования вопроса, результата, ответственного редактора и условий участия. Реестр задач проекта ведётся в Jira; этот раздел показывает только разрешённые публичные сведения."],participants:["Публичные роли пока не объявлены","Здесь будут опубликованы согласованные имена или псевдонимы, реальные полномочия и порядок рассмотрения конфликтов. Участники не получают рейтинг человеческой ценности."],support:["Опубликованных финансовых отчётов пока нет","Появятся сводные сведения о назначении и использовании поддержки. Личные платёжные данные не публикуются."]}[kind];
 return <>{error&&<p className={styles.notice} role="status">{error}</p>}{items.length?items.map((item,index)=><article key={item.id||index} className={styles.card}><p className={styles.meta}>{editorialDate(item.published_at||item.created_at)} {item.edition_id}</p><h2>{item.title||item.question||item.display_name||"Опубликованный материал"}</h2><p className={styles.message}>{item.change_summary||item.summary||item.message}</p>{safeEditorialUrl(item.canonical_url||item.url)&&<a className="text-link" href={safeEditorialUrl(item.canonical_url||item.url)}>Открыть подтверждённый результат</a>}</article>):<div className={styles.empty}><h2>{empty[0]}</h2><p>{empty[1]}</p></div>}{kind==="tasks"&&!meta?.capabilities.research_tasks&&<p className={styles.muted}>Приём заявок на исследование закрыт. У проекта пока нет подключённого публичного каталога согласованных задач.</p>}{loaded&&<span className={styles.srOnly} role="status">Публичные сведения загружены</span>}</>;
}
